/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.2.15.v202410041642.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_EXAMPLE_VEHICLE_Vehicle_DBUS_STUB_ADAPTER_HPP_
#define V1_COM_EXAMPLE_VEHICLE_Vehicle_DBUS_STUB_ADAPTER_HPP_

#include <v1/com/example/vehicle/VehicleStub.hpp>
#include "v1/com/example/vehicle/VehicleDBusDeployment.hpp"

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace example {
namespace vehicle {

template <typename _Stub = ::v1::com::example::vehicle::VehicleStub, typename... _Stubs>
class VehicleDBusStubAdapterInternal
    : public virtual VehicleStubAdapter,
      public CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...>
     {
public:
    typedef CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...> VehicleDBusStubAdapterHelper;

    ~VehicleDBusStubAdapterInternal() {
        deactivateManagedInstances();
        VehicleDBusStubAdapterHelper::deinit();
    }

    virtual bool hasFreedesktopProperties() {
        return false;
    }

    inline static const char* getInterface() {
        return Vehicle::getInterface();
    }

    void fireSpeedAttributeChanged(const uint32_t& value);

    void fireSpeedChangedEvent(const uint32_t& speed);

    void deactivateManagedInstances() {
    }

    CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::com::example::vehicle::VehicleStub,
        CommonAPI::Version
        > getVehicleInterfaceVersionStubDispatcher;

    CommonAPI::DBus::DBusGetAttributeStubDispatcher<
            ::v1::com::example::vehicle::VehicleStub,
            uint32_t,
            CommonAPI::DBus::IntegerDeployment
            > getSpeedAttributeStubDispatcher;
    CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
            ::v1::com::example::vehicle::VehicleStub,
            uint32_t,
            CommonAPI::DBus::IntegerDeployment
            > setSpeedAttributeStubDispatcher;

    
    CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::com::example::vehicle::VehicleStub,
        std::tuple< >,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::DBus::IntegerDeployment>
    
        > getSpeedStubDispatcher;

    
    CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::com::example::vehicle::VehicleStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::DBus::IntegerDeployment>,
        std::tuple< >
    
        > setSpeedStubDispatcher;


    VehicleDBusStubAdapterInternal(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
    : CommonAPI::DBus::DBusStubAdapter(_address, _connection,false),
      VehicleDBusStubAdapterHelper(_address, _connection, false, _stub), 
      getVehicleInterfaceVersionStubDispatcher(&VehicleStub::lockInterfaceVersionAttribute, &VehicleStub::getInterfaceVersion, "uu", true),
      getSpeedAttributeStubDispatcher(
          &::v1::com::example::vehicle::VehicleStub::lockSpeedAttribute,
          &::v1::com::example::vehicle::VehicleStub::getSpeedAttribute,
          "u",
          _stub->hasElement(0)),
      setSpeedAttributeStubDispatcher(
          &::v1::com::example::vehicle::VehicleStub::lockSpeedAttribute,
          &::v1::com::example::vehicle::VehicleStub::getSpeedAttribute,
          &VehicleStubRemoteEvent::onRemoteSetSpeedAttribute,
          &VehicleStubRemoteEvent::onRemoteSpeedAttributeChanged,
          &VehicleStubAdapter::fireSpeedAttributeChanged,
          "u",
          _stub->hasElement(0))
      ,
      getSpeedStubDispatcher(&VehicleStub::getSpeed, "u",
           _stub->hasElement(1), std::make_tuple(), std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)))
      ,
      setSpeedStubDispatcher(&VehicleStub::setSpeed, "",
           _stub->hasElement(2), std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)), std::make_tuple())
    {
        VehicleDBusStubAdapterHelper::addStubDispatcher({ "getSpeedAttribute", "" }, &getSpeedAttributeStubDispatcher);
        VehicleDBusStubAdapterHelper::addStubDispatcher({ "setSpeedAttribute", "u" }, &setSpeedAttributeStubDispatcher);
        VehicleDBusStubAdapterHelper::addStubDispatcher({ "getSpeed", "" }, &getSpeedStubDispatcher);
        VehicleDBusStubAdapterHelper::addStubDispatcher({ "setSpeed", "u" }, &setSpeedStubDispatcher);
        VehicleDBusStubAdapterHelper::addStubDispatcher({ "getInterfaceVersion", "" }, &getVehicleInterfaceVersionStubDispatcher);
    }

protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const {
        static const std::string introspectionData =
            "<method name=\"getInterfaceVersion\">\n"
                "<arg name=\"value\" type=\"uu\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"getSpeedAttribute\">\n"
            "<arg name=\"value\" type=\"u\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"setSpeedAttribute\">\n"
            "<arg name=\"requestedValue\" type=\"u\" direction=\"in\" />\n"
            "<arg name=\"setValue\" type=\"u\" direction=\"out\" />\n"
            "</method>\n"
            "<signal name=\"onSpeedAttributeChanged\">\n"
            "<arg name=\"changedValue\" type=\"u\" />\n"
            "</signal>\n"
            "<signal name=\"speedChanged\">\n"
            "<arg name=\"speed\" type=\"u\" />\n"
            "</signal>\n"
            "<method name=\"getSpeed\">\n"
            "<arg name=\"_speed\" type=\"u\" direction=\"out\" />\n"
            "<annotation name=\"org.freedesktop.DBus.Method.NoReply\" value=\"true\" />\n"
            "</method>\n"
            "<method name=\"setSpeed\">\n"
            "<arg name=\"_speed\" type=\"u\" direction=\"in\" />\n"
            "<annotation name=\"org.freedesktop.DBus.Method.NoReply\" value=\"true\" />\n"
            "</method>\n"
            ;
        return introspectionData.c_str();
    }

private:
};


template <typename _Stub, typename... _Stubs>
void VehicleDBusStubAdapterInternal<_Stub, _Stubs...>::fireSpeedAttributeChanged(const uint32_t& value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deployedValue(value, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<
    CommonAPI::Deployable<
        uint32_t,
        CommonAPI::DBus::IntegerDeployment
    >
    >>
        ::sendSignal(
            *this,
            "onSpeedAttributeChanged",
            "u",
            deployedValue
    
    );
}

template <typename _Stub, typename... _Stubs>
void VehicleDBusStubAdapterInternal<_Stub, _Stubs...>::fireSpeedChangedEvent(const uint32_t& speed) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment>
    >>::sendSignal(
            *this,
            "speedChanged",
            "u",
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment>(speed, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr))
    );
}


template <typename _Stub = ::v1::com::example::vehicle::VehicleStub, typename... _Stubs>
class VehicleDBusStubAdapter
    : public VehicleDBusStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< VehicleDBusStubAdapter<_Stub, _Stubs...>> {
public:
    VehicleDBusStubAdapter(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
        : CommonAPI::DBus::DBusStubAdapter(
            _address,
            _connection,
            false),
          VehicleDBusStubAdapterInternal<_Stub, _Stubs...>(
            _address,
            _connection,
            _stub) {
    }
};

} // namespace vehicle
} // namespace example
} // namespace com
} // namespace v1

#endif // V1_COM_EXAMPLE_VEHICLE_Vehicle_DBUS_STUB_ADAPTER_HPP_
