/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_EXAMPLE_VEHICLE_Vehicle_PROXY_HPP_
#define V1_COM_EXAMPLE_VEHICLE_Vehicle_PROXY_HPP_

#include <v1/com/example/vehicle/VehicleProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace example {
namespace vehicle {

template <typename ... _AttributeExtensions>
class VehicleProxy
    : virtual public Vehicle,
      virtual public VehicleProxyBase,
      virtual public _AttributeExtensions... {
public:
    VehicleProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~VehicleProxy();

    typedef ::v1::com::example::vehicle::Vehicle InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute speed.
     */
    virtual SpeedAttribute& getSpeedAttribute() {
        return delegate_->getSpeedAttribute();
    }
    /**
     * Calls getSpeed with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getSpeed(CommonAPI::CallStatus &_internalCallStatus, uint32_t &_speed, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getSpeed with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getSpeedAsync(GetSpeedAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setSpeed with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void setSpeed(uint32_t _speed, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setSpeed with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> setSpeedAsync(const uint32_t &_speed, SetSpeedAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast speedChanged.
     */
    virtual SpeedChangedEvent& getSpeedChangedEvent() {
        return delegate_->getSpeedChangedEvent();
    }



 private:
    std::shared_ptr< VehicleProxyBase> delegate_;
};

typedef VehicleProxy<> VehicleProxyDefault;

namespace VehicleExtensions {
    template <template <typename > class _ExtensionType>
    class SpeedAttributeExtension {
     public:
        typedef _ExtensionType< VehicleProxyBase::SpeedAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< VehicleProxyBase::SpeedAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SpeedAttributeExtension(VehicleProxyBase& proxy): attributeExtension_(proxy.getSpeedAttribute()) {
        }
    
        inline extension_type& getSpeedAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace VehicleExtensions

//
// VehicleProxy Implementation
//
template <typename ... _AttributeExtensions>
VehicleProxy<_AttributeExtensions...>::VehicleProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< VehicleProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< VehicleProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
VehicleProxy<_AttributeExtensions...>::~VehicleProxy() {
}

template <typename ... _AttributeExtensions>
void VehicleProxy<_AttributeExtensions...>::getSpeed(CommonAPI::CallStatus &_internalCallStatus, uint32_t &_speed, const CommonAPI::CallInfo *_info) {
    delegate_->getSpeed(_internalCallStatus, _speed, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> VehicleProxy<_AttributeExtensions...>::getSpeedAsync(GetSpeedAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getSpeedAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void VehicleProxy<_AttributeExtensions...>::setSpeed(uint32_t _speed, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->setSpeed(_speed, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> VehicleProxy<_AttributeExtensions...>::setSpeedAsync(const uint32_t &_speed, SetSpeedAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->setSpeedAsync(_speed, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &VehicleProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool VehicleProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool VehicleProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& VehicleProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& VehicleProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> VehicleProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace vehicle
} // namespace example
} // namespace com
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::com::example::vehicle::VehicleProxy,
    _AttributeExtension> {
    typedef typename ::v1::com::example::vehicle::VehicleProxy<
            ::v1::com::example::vehicle::VehicleExtensions::SpeedAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_EXAMPLE_VEHICLE_Vehicle_PROXY_HPP_
