/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.2.15.v202410041642.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/com/example/vehicle/Vehicle.hpp>
#include <v1/com/example/vehicle/VehicleDBusStubAdapter.hpp>

namespace v1 {
namespace com {
namespace example {
namespace vehicle {

std::shared_ptr<CommonAPI::DBus::DBusStubAdapter> createVehicleDBusStubAdapter(
                   const CommonAPI::DBus::DBusAddress &_address,
                   const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< VehicleDBusStubAdapter<::v1::com::example::vehicle::VehicleStub>>(_address, _connection, std::dynamic_pointer_cast<::v1::com::example::vehicle::VehicleStub>(_stub));
}

void initializeVehicleDBusStubAdapter() {
    CommonAPI::DBus::Factory::get()->registerStubAdapterCreateMethod(
        Vehicle::getInterface(), &createVehicleDBusStubAdapter);
}

INITIALIZER(registerVehicleDBusStubAdapter) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeVehicleDBusStubAdapter);
}

} // namespace vehicle
} // namespace example
} // namespace com
} // namespace v1
