/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.2.15.v202410041642.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/com/example/vehicle/VehicleDBusProxy.hpp>

namespace v1 {
namespace com {
namespace example {
namespace vehicle {

std::shared_ptr<CommonAPI::DBus::DBusProxy> createVehicleDBusProxy(
    const CommonAPI::DBus::DBusAddress &_address,
    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection) {
    return std::make_shared< VehicleDBusProxy>(_address, _connection);
}

void initializeVehicleDBusProxy() {
     CommonAPI::DBus::Factory::get()->registerProxyCreateMethod(
        Vehicle::getInterface(),
        &createVehicleDBusProxy);
}

INITIALIZER(registerVehicleDBusProxy) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeVehicleDBusProxy);
}

VehicleDBusProxy::VehicleDBusProxy(
    const CommonAPI::DBus::DBusAddress &_address,
    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection)
    :   CommonAPI::DBus::DBusProxy(_address, _connection)
,        speed_(*this, "onSpeedAttributeChanged", "setSpeedAttribute", "u", "getSpeedAttribute", static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr))
,        speedChanged_(*this, "speedChanged", "u", std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)))
{
}

VehicleDBusProxy::~VehicleDBusProxy() {
    completed_.set_value();
}

VehicleDBusProxy::SpeedAttribute& VehicleDBusProxy::getSpeedAttribute() {
    return speed_;
}

VehicleDBusProxy::SpeedChangedEvent& VehicleDBusProxy::getSpeedChangedEvent() {
    return speedChanged_;
}

void VehicleDBusProxy::getSpeed(CommonAPI::CallStatus &_internalCallStatus, uint32_t &_speed, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_speed(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
    CommonAPI::DBus::DBusProxyHelper<
        CommonAPI::DBus::DBusSerializableArguments<
        >,
        CommonAPI::DBus::DBusSerializableArguments<
        CommonAPI::Deployable< uint32_t,CommonAPI::DBus::IntegerDeployment>
        >
        >::callMethodWithReply(
        *this,
        "getSpeed",
        "",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        _internalCallStatus,
        deploy_speed);
    _speed = deploy_speed.getValue();
}

std::future<CommonAPI::CallStatus> VehicleDBusProxy::getSpeedAsync(GetSpeedAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_speed(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
    return CommonAPI::DBus::DBusProxyHelper<
        CommonAPI::DBus::DBusSerializableArguments<
        >,
        CommonAPI::DBus::DBusSerializableArguments<
        CommonAPI::Deployable< uint32_t,CommonAPI::DBus::IntegerDeployment>
        >
        >::callMethodAsync(
        *this,
        "getSpeed",
        "",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment > _speed) {
            if (_callback)
                _callback(_internalCallStatus, _speed.getValue());
        },
        std::make_tuple(deploy_speed));
}
void VehicleDBusProxy::setSpeed(uint32_t _speed, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_speed(_speed, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
    CommonAPI::DBus::DBusProxyHelper<
        CommonAPI::DBus::DBusSerializableArguments<
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >
        >,
        CommonAPI::DBus::DBusSerializableArguments<
        >
        >::callMethodWithReply(
        *this,
        "setSpeed",
        "u",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_speed,
        _internalCallStatus);
}

std::future<CommonAPI::CallStatus> VehicleDBusProxy::setSpeedAsync(const uint32_t &_speed, SetSpeedAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_speed(_speed, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
    return CommonAPI::DBus::DBusProxyHelper<
        CommonAPI::DBus::DBusSerializableArguments<
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >
        >,
        CommonAPI::DBus::DBusSerializableArguments<
        >
        >::callMethodAsync(
        *this,
        "setSpeed",
        "u",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_speed,
        [_callback] (CommonAPI::CallStatus _internalCallStatus) {
            if (_callback)
                _callback(_internalCallStatus);
        },
        std::make_tuple());
}


void VehicleDBusProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> VehicleDBusProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace vehicle
} // namespace example
} // namespace com
} // namespace v1
