/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.2.15.v202410041642.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_EXAMPLE_VEHICLE_Vehicle_DBUS_PROXY_HPP_
#define V1_COM_EXAMPLE_VEHICLE_Vehicle_DBUS_PROXY_HPP_

#include <v1/com/example/vehicle/VehicleProxyBase.hpp>
#include "v1/com/example/vehicle/VehicleDBusDeployment.hpp"

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/DBus/DBusAddress.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusProxy.hpp>
#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusAttribute.hpp>
#include <CommonAPI/DBus/DBusEvent.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace com {
namespace example {
namespace vehicle {

class VehicleDBusProxy
    : virtual public VehicleProxyBase,
      virtual public CommonAPI::DBus::DBusProxy {
public:
    VehicleDBusProxy(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection);

    virtual ~VehicleDBusProxy();

    virtual SpeedAttribute& getSpeedAttribute();

    virtual SpeedChangedEvent& getSpeedChangedEvent();

    virtual void getSpeed(CommonAPI::CallStatus &_internalCallStatus, uint32_t &_speed, const CommonAPI::CallInfo *_info);
    virtual std::future<CommonAPI::CallStatus> getSpeedAsync(GetSpeedAsyncCallback _callback, const CommonAPI::CallInfo *_info);
    virtual void setSpeed(uint32_t _speed, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info);
    virtual std::future<CommonAPI::CallStatus> setSpeedAsync(const uint32_t &_speed, SetSpeedAsyncCallback _callback, const CommonAPI::CallInfo *_info);


    virtual void getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const;

    virtual std::future<void> getCompletionFuture();

private:

    CommonAPI::DBus::DBusObservableAttribute<CommonAPI::DBus::DBusAttribute<SpeedAttribute, CommonAPI::DBus::IntegerDeployment>> speed_;

    CommonAPI::DBus::DBusEvent<SpeedChangedEvent, CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >> speedChanged_;


    std::promise<void> completed_;
};

} // namespace vehicle
} // namespace example
} // namespace com
} // namespace v1

#endif // V1_COM_EXAMPLE_VEHICLE_Vehicle_DBUS_PROXY_HPP_

