/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_EXAMPLE_VEHICLE_Vehicle_STUB_HPP_
#define V1_COM_EXAMPLE_VEHICLE_Vehicle_STUB_HPP_

#include <functional>
#include <sstream>






#include <v1/com/example/vehicle/Vehicle.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <unordered_set>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace example {
namespace vehicle {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service Vehicle. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class VehicleStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual Vehicle {
 public:
    ///Notifies all remote listeners about a change of value of the attribute speed.
    virtual void fireSpeedAttributeChanged(const uint32_t &speed) = 0;
    /**
    * Sends a broadcast event for speedChanged. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSpeedChangedEvent(const uint32_t &_speed) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockSpeedAttribute(bool _lockAccess) {
        if (_lockAccess) {
            speedMutex_.lock();
        } else {
            speedMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex speedMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for Vehicle.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class VehicleStubRemoteEvent
{
public:
    virtual ~VehicleStubRemoteEvent() { }

    /// Verification callback for remote set requests on the attribute speed
    virtual bool onRemoteSetSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) = 0;
    /// Action callback for remote set requests on the attribute speed
    virtual void onRemoteSpeedAttributeChanged() = 0;
};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service Vehicle to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class VehicleStub
    : public virtual CommonAPI::Stub<VehicleStubAdapter, VehicleStubRemoteEvent>
{
public:
    typedef std::function<void (uint32_t _speed)> getSpeedReply_t;
    typedef std::function<void ()> setSpeedReply_t;

    virtual ~VehicleStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 4);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute speed
    virtual const uint32_t &getSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireSpeedAttributeChanged(uint32_t _value) {
    auto stubAdapter = CommonAPI::Stub<VehicleStubAdapter, VehicleStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireSpeedAttributeChanged(_value);
    }
    void lockSpeedAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<VehicleStubAdapter, VehicleStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockSpeedAttribute(_lockAccess);
    }
    /// This is the method that will be called on remote calls on the method getSpeed.
    virtual void getSpeed(const std::shared_ptr<CommonAPI::ClientId> _client, getSpeedReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method setSpeed.
    virtual void setSpeed(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _speed, setSpeedReply_t _reply) = 0;
    /// Sends a broadcast event for speedChanged.
    virtual void fireSpeedChangedEvent(const uint32_t &_speed) {
        auto stubAdapter = CommonAPI::Stub<VehicleStubAdapter, VehicleStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSpeedChangedEvent(_speed);
    }


    using CommonAPI::Stub<VehicleStubAdapter, VehicleStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<VehicleStubAdapter, VehicleStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<VehicleStubAdapter, VehicleStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef VehicleStubRemoteEvent RemoteEventType;
    typedef ::v1::com::example::vehicle::Vehicle StubInterface;
};

} // namespace vehicle
} // namespace example
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_EXAMPLE_VEHICLE_Vehicle_STUB_HPP_
