/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_EXAMPLE_VEHICLE_Vehicle_PROXY_BASE_HPP_
#define V1_COM_EXAMPLE_VEHICLE_Vehicle_PROXY_BASE_HPP_

#include <v1/com/example/vehicle/Vehicle.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <vector>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace example {
namespace vehicle {

class VehicleProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableAttribute<uint32_t> SpeedAttribute;
    typedef CommonAPI::Event<
        uint32_t
    > SpeedChangedEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const uint32_t&)> GetSpeedAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> SetSpeedAsyncCallback;

    virtual SpeedAttribute& getSpeedAttribute() = 0;
    virtual void getSpeed(CommonAPI::CallStatus &_internalCallStatus, uint32_t &_speed, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getSpeedAsync(GetSpeedAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void setSpeed(uint32_t _speed, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> setSpeedAsync(const uint32_t &_speed, SetSpeedAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual SpeedChangedEvent& getSpeedChangedEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace vehicle
} // namespace example
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_EXAMPLE_VEHICLE_Vehicle_PROXY_BASE_HPP_
